# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: app
    url: https://app.xceedcore.com
  - name: landing page
    url: https://shop.xceedcore.com/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Xceedcore Status
  introTitle: This is the up-time tracker for xceedcore websites
  introMessage: This is the up-time tracker for xceedcore websites

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
